### ISSUE TITLE
Suggestion: menu functionality

### ISSUE THREAD

**Issue by bzenky** [diego3g/faladev#5]
I was thinking in oppening a PR with a dropdown,  containing your social links when user clicks in user icon, something like happen in VS Code. I don't know if it's part of your plan develop the nav menu, so if it's worth it, I start the PR here.

**Comment by diego3g** [comment]
Yeah, I think it would be very cool.

**Comment by bzenky** [comment]
I'm closing this issue as it is being developed in PR https://github.com/diego3g/faladev/pull/6
