### ISSUE TITLE
Mobile viewport fix

### ISSUE THREAD

**Issue by hqnicolas** [diego3g/faladev#9]
### Problem:

The desktop version works fine on mobile devices, however the mobile version does not.
User-Agent detection: as some mobile devices may report their user-agent string as a desktop browser to work around compatibility issues.

###  Solution:

`
'''HTML
head
  <meta name="viewport" content="width=1024">
/head
`

![hqnicolas-faladev](https://user-images.githubusercontent.com/41456803/219707621-7230ed3b-5e80-47a0-9202-798d4f3af89f.jpeg)

**Comment by diego3g** [comment]
Can you please send a PR?

**Comment by hqnicolas** [comment]
Solved 
https://github.com/diego3g/faladev/pull/13
